### PR TITLE
added linux build

### PR DESCRIPTION
**Pull request by trevortomesh**
I added a linux build folder to dist and included the built .love file. Can also add build instructions to either main README file or withing dist/linux if required.

### CODE REVIEW

**Comment by kennethreitz** [comment]
well a .love file can be built from any machine, that's the easy part ;)

**Comment by kennethreitz** [comment]
let's shoot for getting a debian package made!

**Comment by kennethreitz** [comment]
https://wiki.debian.org/Games/Love2d

**Comment by trevortomesh** [comment]
Not a problem. Didn't know that's what we were shooting for! Will pull again with a .deb

**Pull request closed without merging**
